include ../make/Makefile.dirs


DIRS = \
       addressbook \
       piqi \
       perf \
       packed \
       array \
       misc \
       custom-types \
       piq-config \

ifneq ($(shell which protoc), )
DIRS += riak_pb
endif
